import { box, cover, say, type Niche } from "./niches";
import type { Slide } from "./templates";

/** Английский финальный слайд. Русский — в niches.ts, рядом с наборами. */
export const ENDING_EN: Slide = {
  kind: "final",
  eyebrow: "one last thing",
  title: "Save this before you scroll on",
  body: "You will not find it again by searching — the good ones never come back up in the feed.",
  code: "",
  takeaway: "Save · Share",
  photo: false,
};

/*
  Английские наборы. Отдельным файлом, как у промтов: русский и
  английский растут независимо, и держать их в одном файле — значит
  каждый раз листать чужой язык, чтобы дойти до своего.
*/

export const NICHES_EN: Niche[] = [
  {
    id: "ai",
    title: "AI and prompts",
    decks: [
      { id: "ai-1", title: "5 prompts that save an hour a day", slides: [
        cover("AI · prompts", "I wrote 400 prompts. Five work", "copy them as they are →"),
        say("why most fail", "A prompt is not a spell.", "It works when it gives the model three things: a role, a constraint, and a test it can use to know it succeeded.", "Role · Constraint · Test"),
        box("prompt · 1", "My voice, not the average one", "Here are 3 of my texts. List the rules of my style, show me the list, and only then write.", "The text stops smelling of AI"),
        say("the point", "Five cover a whole week", "I deleted the other 395. Not because they were bad — because I never opened them twice.", "Save this so you stop searching"),
      ]},
      { id: "ai-2", title: "Beginner mistakes with AI", slides: [
        cover("teardown", "7 reasons the model answers beside the point", "one per slide →"),
        say("mistake 1", "You ask for the result first", "The model does not know your context. Give the inputs, then the task — otherwise it fills the gap itself.", "Inputs first, request second"),
        say("mistake 2", "You never say what is wrong", "“Make it better” means nothing. Say what is off: too long, too dry, aimed at the wrong people.", "Criticism beats praise"),
        say("the point", "It is not the model", "The same model answers two people differently. The difference is what they told it.", "Save before your next request"),
      ]},
      { id: "ai-3", title: "AI in 30 minutes a day", slides: [
        cover("routine", "30 minutes with AI instead of three hours by hand", "the schedule →"),
        say("what to give it", "Give it the cheap mistakes", "Drafts, lists, headline options. The error shows immediately and costs one minute.", "Cheap mistake: hand it over"),
        say("what to keep", "Keep what surfaces a month later", "Positioning, pricing, a type pairing. A miss is noticed late and everything gets redone.", "Expensive mistake: by hand"),
        say("the point", "Count in weeks", "A two-minute task ten times a day costs more than an hour once a month. Automate the first.", "Save and audit your own week"),
      ]},
      { id: "ai-4", title: "How to spot AI writing", slides: [
        cover("check", "How to tell in 10 seconds that a model wrote it", "5 tells →"),
        say("tell 1", "Everything is even and nothing catches", "Identical paragraph lengths, not one rough edge. People write unevenly.", "Evenness is not a virtue"),
        say("tell 2", "Polite filler", "“It is important to note”, “in today's world”. Neither says anything at all.", "Cut them, nothing is lost"),
        say("the point", "One question fixes it", "Ask: what here could only this person have written? If nothing, rewrite it.", "Save before publishing"),
      ]},
      { id: "ai-5", title: "A prompt for competitor teardowns", slides: [
        cover("AI · teardown", "I take a competitor apart in 15 minutes", "prompt inside →"),
        say("why", "Looking is not understanding", "You can scroll a competitor's site for an hour and miss who it sells to. Questions beat attention.", "A teardown is a question list"),
        box("prompt", "Taking a page apart", "Here is a competitor's page. Tell me: who it sells to, the hero promise, where an objection is answered, what to take, and how to rework it for a different product.", "Three ideas instead of an hour"),
        say("the point", "Do not copy the words", "Take the device, not the text. Their text stands on their proof; yours is different.", "Save for the next teardown"),
      ]},
      { id: "ai-6", title: "Myths about AI", slides: [
        cover("myths", "4 myths people still believe about AI", "one at a time →"),
        say("myth 1", "“AI will replace the job”", "It is not the tool that replaces you but the person using it. The difference is who asks the questions.", "The tool replaces nobody"),
        say("myth 2", "“You need the perfect prompt”", "There is none. There is a short conversation: ask, correct, correct. Three moves, not one spell.", "A dialogue, not a spell"),
        say("the point", "Settle it in one evening", "Take your own task and do it twice, by hand and with a model. The argument ends itself.", "Save and test it yourself"),
      ]},
      { id: "ai-7", title: "How to ask so you get answers", slides: [
        cover("skill", "The question matters more than the model", "how to ask →"),
        say("rule 1", "Show an example of what you want", "One example of the right output saves ten clarifications. Models read samples better than descriptions.", "Show, do not describe"),
        say("rule 2", "Say what must not appear", "Bans work harder than requests: no lists, no preamble, never the word “innovative”.", "A never list is mandatory"),
        say("the point", "Phrasing is the work", "Five minutes on the question saves half an hour of rewriting. That is order, not laziness.", "Save and try it tomorrow"),
      ]},
      { id: "ai-8", title: "What not to trust AI with", slides: [
        cover("careful", "5 things I never hand to a model", "from experience →"),
        say("first", "Numbers nobody will check", "A model produces the plausible, not the true. A figure with no source is a guess in a nice font.", "Check every number"),
        say("second", "Other people's personal data", "A client's messages, an ID, a medical note. Not yours to share.", "Other people's stays out"),
        say("the point", "One-line rule", "If the mistake would be noticed late and cost a lot, do it by hand.", "Save and reread before sending"),
      ]},
      { id: "ai-9", title: "A prompt for a content plan", slides: [
        cover("AI · content", "A month of content in 20 minutes", "prompt inside →"),
        say("why it stalls", "Plans do not die of laziness", "They die when they hold thirty unrelated ideas. You need formats, not thirty ideas.", "Formats survive the month"),
        box("prompt", "A plan built on formats", "My subject and audience: ... Build 4 recurring formats, 4 posts in each. For every post give the opening line and what the reader takes away. No preamble.", "16 posts you will not abandon"),
        say("the point", "Fewer formats, more posts", "Four formats can run a year. Thirty ideas run out at number eight.", "Save before you plan"),
      ]},
      { id: "ai-10", title: "Where to start with AI", slides: [
        cover("start", "Start with one task, not ten", "the first month →"),
        say("step 1", "Take what you do every day", "Not the hardest thing — the most frequent. Savings are counted in weeks, not in one impressive result.", "Frequent beats complex"),
        say("step 2", "Compare with how it was", "Time it before and after. Without a number you will not remember in a month whether it helped.", "Measure before and after"),
        say("the point", "One task, four weeks", "When it becomes a habit, take the second. Ten at once never stick.", "Save and pick your one"),
      ]},
    ],
  },
  {
    id: "marketplace",
    title: "Marketplaces",
    decks: [
      { id: "mp-1", title: "Why your listing does not sell", slides: [
        cover("teardown", "1,200 impressions, 3 orders. Here is why", "step by step →"),
        say("step 1", "Judge the thumbnail, not the photo", "In the grid your shot is the size of a fingernail. If the silhouette does not read, stop there.", "Silhouette first, detail later"),
        say("step 2", "The first 60 characters of the title", "That is what shows in the grid. Type and main attribute belong there.", "The click is decided in line one"),
        say("the point", "Impressions but no clicks", "That is always the photo and the title. The description fixes a different problem: returns.", "Save before you edit"),
      ]},
      { id: "mp-2", title: "5 beginner mistakes", slides: [
        cover("mistakes", "5 mistakes that cost me $2,000", "one at a time →"),
        say("mistake 1", "Ordered against average demand", "One double week empties the shelf, and zero stock removes the listing from the grid.", "Plan on spread, not average"),
        say("mistake 2", "Joined a promotion without maths", "Margin drops threefold, sales double. The result is negative and only visible at month end.", "Count currency per unit"),
        say("the point", "All five are about counting", "Not photos, not ads. About numbers computed before, not after.", "Save before your next order"),
      ]},
      { id: "mp-3", title: "How to answer bad reviews", slides: [
        cover("reputation", "I do not write to the reviewer. Here is who I write to", "and why →"),
        say("the key", "The next buyer reads it", "The author already decided. Your reply works on the hundred people scrolling reviews before buying.", "Write for the next one"),
        say("how", "A fact, not an apology", "“We apologise” says nothing. “In the 12 August batch the gasket shipped separately” does.", "Facts remove fear"),
        say("the point", "Ratings recover through goods", "Replies help, but the product matters more. Bought reviews are visible to everyone.", "Save for the next reply"),
      ]},
      { id: "mp-4", title: "What is actually left", slides: [
        cover("money", "Sold $40,000 worth. Kept $3,800", "line by line →"),
        say("what eats it", "Commission is not the only thing", "Shipping out, shipping back, storage, payment fees, ads. And returns, which cost twice.", "Compute after returns"),
        say("rule", "Margin in currency, not percent", "Percentages hide the case where every sale loses money. Currency per unit hides nothing.", "Currency is honest"),
        say("the point", "Revenue is not income", "A line with huge turnover and no margin looks like the leader right up until you count.", "Save and recount your top line"),
      ]},
      { id: "mp-5", title: "What to shoot for a listing", slides: [
        cover("photos", "8 shots that answer 90% of questions", "the list →"),
        say("shot 1", "Scale beside a hand", "“How big is it” is the most asked question in chat. One frame ends it forever.", "Size is the first question"),
        say("shot 2", "The underside and the box contents", "These cut returns most: the buyer sees what arrives before ordering.", "Fewer surprises, fewer returns"),
        say("the point", "Empty slots cost more than average photos", "An unfinished gallery damages trust more than an imperfect frame.", "Save before the shoot"),
      ]},
      { id: "mp-6", title: "The listing dropped", slides: [
        cover("panic", "The listing dropped. What to check, in order", "no skipping →"),
        say("first", "Stock", "Zero stock removes a listing from the grid. It is cause number one and it is checked first.", "Warehouse before anything"),
        say("second", "Listing edits", "Changing a title or category recalculates relevance and sinks you for a few days.", "Edits cost position"),
        say("the point", "One cause, not a list", "Five named causes means none was checked. Find the one that matches the date.", "Save and work the order"),
      ]},
      { id: "mp-7", title: "How to pick a niche", slides: [
        cover("start", "I picked a niche in three evenings", "the steps →"),
        say("step 1", "Look at competition, not demand", "High demand with a hundred established sellers is someone else's market, not yours.", "Demand without room is not a chance"),
        say("step 2", "Do the maths before buying", "Cost, commission, logistics, returns. Under 25% margin the niche forgives no mistakes.", "25% is the floor"),
        say("the point", "Test with a small batch", "Not your first thousand. Fifty units answer the question cheaper than any analysis.", "Save before you choose"),
      ]},
      { id: "mp-8", title: "Working with suppliers", slides: [
        cover("sourcing", "One question that saved me $1,000", "and four more →"),
        say("the question", "“What defect rate do you consider normal?”", "Dodging is itself an answer. Ask before paying, not after receiving.", "A dodge is an answer"),
        say("receiving", "Open cartons at random", "Twenty units from a batch of 500, and not off the top. The top is always the good stuff.", "Random, not the top layer"),
        say("the point", "Photograph while opening", "A claim without photos is refused almost everywhere. Shoot labels and every defect.", "Save before receiving"),
      ]},
      { id: "mp-9", title: "Launching a new product", slides: [
        cover("launch", "The first 30 days, week by week", "the plan →"),
        say("week 1", "The goal is first orders", "No reviews, no trust, low conversion. That is normal and budgeted, not a failure.", "Low conversion is expected"),
        say("week 2", "Reviews the honest way", "An insert in the packaging. Not “leave five stars” but “tell us what is wrong”.", "Ask for truth, not a score"),
        say("the point", "Set the stop number first", "Name it before launch. Once money is spent, stopping is never chosen.", "Save and set your own"),
      ]},
      { id: "mp-10", title: "What to check daily", slides: [
        cover("routine", "3 numbers I check every morning", "and why these →"),
        say("number 1", "Days to zero", "Not units left but time left. A 35-day lead time means ordering long before the shelf empties.", "Time beats units"),
        say("number 2", "Return rate over 7 days", "A jump within a week means a batch, not customers. Only a short window catches it.", "A week catches a batch"),
        say("the point", "Three minutes a day", "Everything else is weekly. Daily analytics eats time and decides nothing.", "Save and build the habit"),
      ]},
    ],
  },
  {
    id: "smm",
    title: "Social media",
    decks: [
      { id: "smm-1", title: "Why posts do not land", slides: [
        cover("reach", "40 posts. Two worked. Here is the difference", "slide by slide →"),
        say("the cause", "Your first line promises a talk", "“I want to share some thoughts” promises reading. People scroll on, because they never planned to read.", "Promise a result, not a talk"),
        say("the fix", "Open on a moment", "“At 7:40pm on Friday the client wrote that launch was tomorrow” holds. Save the lesson for the end.", "A moment, not a conclusion"),
        say("the point", "The topic was not the problem", "Same two thoughts, different first line, twenty times the reach.", "Save before your next post"),
      ]},
      { id: "smm-2", title: "A content plan you will not abandon", slides: [
        cover("system", "Four formats instead of thirty ideas", "how it works →"),
        say("why", "Ideas run out, formats do not", "Thirty topics last a week. Four formats can run a year, because you only think about filling them.", "A format is a shape"),
        say("which", "Teardown · Mistake · Tool · Recap", "Four shapes that fit any subject and do not tire the reader.", "Shape beats topic"),
        say("the point", "A month planned in one evening", "Sixteen posts, each in a familiar shape. Not one “what should I write about”.", "Save and pick your four"),
      ]},
      { id: "smm-3", title: "How to write for saves", slides: [
        cover("saves", "A save outweighs a like. Here is how to earn one", "5 devices →"),
        say("device 1", "Give them something to return to", "A list, an order of steps, a formula. Thoughts are rarely saved; instructions constantly are.", "Instructions get saved"),
        say("device 2", "Say it: save this", "Asking out loud works measurably better than hoping. One line at the end.", "Asking is not embarrassing"),
        say("the point", "Be useful the second time", "A good post rewards rereading. If there is nothing to reread, there is nothing to save.", "Save and audit your posts"),
      ]},
      { id: "smm-4", title: "30 minutes a day", slides: [
        cover("routine", "30 minutes a day. Here is what fits", "by the minute →"),
        say("15 minutes", "Replies under other people's posts", "Growth comes from here, not from your own posts. The first twenty minutes after someone posts are gold.", "Replies beat posts"),
        say("7 minutes", "Your post, built from yesterday's reply", "A comment longer than three lines is already a post. Nothing to invent.", "Replies are drafts"),
        say("the point", "More is not better", "An hour a day is abandoned in two weeks. Thirty minutes lasts months.", "Save and try a week"),
      ]},
      { id: "smm-5", title: "Eight opening lines", slides: [
        cover("hooks", "One idea. Eight opening lines", "pick one →"),
        say("mechanics", "Question · Number · Mistake · Disagreement", "Four of the eight. Each works differently: a number promises specifics, a mistake promises recognition.", "Mechanism, not wording"),
        say("rule", "Under eight words", "Longer and they are already scrolling. The feed shows one line and half of the next.", "8 words is the ceiling"),
        say("the point", "Test one at a time", "Change the hook and you change everything. Two changes at once test nothing.", "Save the mechanics list"),
      ]},
      { id: "smm-6", title: "When reach drops", slides: [
        cover("decline", "Reach dropped. What to do and what not to", "in order →"),
        say("wait", "Two days is not a drop", "Reacting before a week means fixing something that is not there.", "A week is the minimum"),
        say("check", "What changed on your side", "Links in posts, a change of subject, posting less, no longer replying in comments.", "Look for date matches"),
        say("the point", "Change one thing", "Five changes at once and you will not know which worked. One change, seven days.", "Save for the quiet week"),
      ]},
      { id: "smm-7", title: "How to answer comments", slides: [
        cover("replies", "Comments are half of the growth", "how to answer →"),
        say("rule 1", "Answer within thirty minutes", "Discussion has a short life. A reply a day later is read only by its author.", "Speed beats wording"),
        say("rule 2", "Do not thank — continue", "“Thanks” closes a thread. A question keeps it open, and open threads carry reach.", "A question, not a thank you"),
        say("the point", "A silent author loses the post", "A post with no author replies dies twice as fast. This is the cheapest work available.", "Save before you publish"),
      ]},
      { id: "smm-8", title: "A personal brand without posing", slides: [
        cover("brand", "A personal brand is not about success", "then what →"),
        say("what works", "Show what you discarded", "Everyone shows the wins. Almost nobody talks about what failed — and those are the ones remembered.", "Failure sets you apart"),
        say("what does not", "Quotes and inspiration", "They get scrolled, not saved and not retold. Retelling is the growth.", "Inspiration is not retold"),
        say("the point", "An angle, not a topic", "“About prompts” is a topic. “About prompts from someone who binned half” is an angle.", "Save and find your angle"),
      ]},
      { id: "smm-9", title: "Writing your bio", slides: [
        cover("profile", "A bio is decided in three seconds", "line by line →"),
        say("line 1", "What the reader gets here", "Not a job title and not a list of credentials. One benefit, in the reader's words.", "Benefit, not job title"),
        say("line 2", "Who it is for", "Narrow beats broad: “for marketplace sellers” brings fewer people and more follows.", "Narrow means clear"),
        say("the point", "Test it on a stranger", "Show the bio to someone who does not know you and ask what the account is about.", "Save and test yours"),
      ]},
      { id: "smm-10", title: "Post-mortem on a flop", slides: [
        cover("analysis", "The post flopped. Where exactly it broke", "by the numbers →"),
        say("low impressions", "Not the post", "Normal completion with low impressions points at links, tags, or posting time.", "Impressions are not the text"),
        say("low completion", "The first line or the middle", "Find where they leave. A dip in the middle is the switch into explaining.", "Find the second it broke"),
        say("the point", "One cause, one change", "Five named causes means none was checked. The algorithm explains the first case, not the third.", "Save for the next one"),
      ]},
    ],
  },
  {
    id: "business",
    title: "Small business",
    decks: [
      { id: "biz-1", title: "Why customers do not come back", slides: [
        cover("retention", "They bought once and vanished", "here is why →"),
        say("the cause", "They simply forgot you", "Not offended, not poached. Six months of silence passed between purchases.", "Silence costs more than a discount"),
        say("the fix", "One reason to write", "Not a newsletter but something specific: the thing they bought is back in stock. One email, one reason.", "A reason, not a reminder"),
        say("the point", "Returning is cheaper than finding", "A new customer costs several times more. Count the people who already paid you.", "Save and write to ten"),
      ]},
      { id: "biz-2", title: "How to price a service", slides: [
        cover("money", "I priced against the market and worked at a loss", "how to price →"),
        say("mistake", "Looking at competitors", "They have different costs and a different pipeline. Their price says nothing about yours.", "Their price is not a guide"),
        say("instead", "From your hour and your load", "How many hours it takes, how many exist in a month, how many are billable. Usually half.", "Not every hour is billable"),
        say("the point", "Raising 20% is easier than it sounds", "A handful leave and revenue rises immediately. Test it on new clients, risk-free.", "Save and recalculate"),
      ]},
      { id: "biz-3", title: "Your first hire", slides: [
        cover("team", "I hired my first person. What I would change", "5 lessons →"),
        say("lesson 1", "Hire for a task, not to “help”", "A vague role ends with someone waiting for instructions while you work more than before.", "A role is a task list"),
        say("lesson 2", "Describe what good looks like", "Without a test they cannot know they succeeded, and you cannot know what to praise.", "The test beats the manual"),
        say("the point", "Month one you work more", "That is normal and it ends. If month three is not easier, the task is wrong, not the person.", "Save before you hire"),
      ]},
      { id: "biz-4", title: "When there are no orders", slides: [
        cover("silence", "A month with no orders. What I did", "step by step →"),
        say("step 1", "Write to people who already bought", "Twenty personal messages beat a week of ads. And they cost nothing.", "Your own first"),
        say("step 2", "Ask the ones who said no", "People who asked and did not buy are the most honest source. Write the same day.", "A refusal explains more than a yes"),
        say("the point", "Silence is not cured by waiting", "It is cured by twenty conversations. Ads come after you know what to fix.", "Save for that month"),
      ]},
      { id: "biz-5", title: "How to count advertising", slides: [
        cover("ads", "I burned $800. I did not know one number", "which one →"),
        say("the number", "Cost per customer, not per click", "Cheap clicks with no sales are expensive advertising. Count to payment, not to visit.", "A click is not a buyer"),
        say("the limit", "Name it before you start", "Once money is spent, stopping feels wasteful. The limit is written in advance.", "The limit comes first"),
        say("the point", "Three numbers are enough", "Cost per customer, average order, repeat share. The rest decorates the report.", "Save before you launch"),
      ]},
      { id: "biz-6", title: "Talking about price", slides: [
        cover("sales", "“Too expensive.” What to say and what not to", "the breakdown →"),
        say("first", "Find out what the word hides", "It means “I do not see the value”, “no money now”, or “I found it cheaper”. Three different answers.", "Ask before you answer"),
        say("never say", "“But our quality”", "That answers nothing. Nor does “it is only a dollar a day” — you are arguing with their arithmetic.", "Do not fight their maths"),
        say("the point", "A discount is the last move", "It devalues everything said before it. First change the scope, the timing, the contents.", "Save for the next call"),
      ]},
      { id: "biz-7", title: "How not to burn out", slides: [
        cover("energy", "Worked 12 hours. Same revenue", "what I changed →"),
        say("first", "Separate the work from the business", "Doing and building are different. Twelve hours of doing move the business nowhere.", "Hands do not build systems"),
        say("second", "One day without clients", "Not a day off but a day working on the business rather than in it. Without it there is no growth.", "One system day a week"),
        say("the point", "Burnout is not about hours", "It is about seeing no movement. Measure one number a month and it gets easier.", "Save and book your day"),
      ]},
      { id: "biz-8", title: "Three lines in a contract", slides: [
        cover("terms", "Three lines that ended every argument", "which ones →"),
        say("line 1", "How many revisions are included", "Without a number revisions are endless and refusing looks like a whim. With one it is a term you agreed.", "A number ends the argument"),
        say("line 2", "What counts as a revision", "Lighting and sound: a revision. Changing the presenter: new work. Written before the start.", "Definition beats number"),
        say("the point", "A contract protects both", "The client does not want an argument either. They want to know what to expect.", "Save and add yours"),
      ]},
      { id: "biz-9", title: "Your first ten clients", slides: [
        cover("start", "First ten clients without ads", "how I found them →"),
        say("step 1", "Twenty specific emails", "Not two hundred identical ones. Each with a hook from their work, not a story about you.", "Specific beats mass"),
        say("step 2", "The smallest possible first step", "Not “let us jump on a call”. A call is a commitment. Offer something read in five minutes.", "A small step, not a meeting"),
        say("the point", "The first ten are by hand", "Ads scale what works. Until it works there is nothing to scale.", "Save and write your first five"),
      ]},
      { id: "biz-10", title: "What to measure weekly", slides: [
        cover("numbers", "Five numbers instead of a hundred", "which →"),
        say("rule", "Only what changes a decision", "A metric you will act on never is decoration and spent time.", "No decision, no metric"),
        say("compare", "Against the same week last year", "Holidays and season move numbers more than your work. Week on week lies.", "Season fools comparison"),
        say("the point", "Fifteen minutes on Friday", "That is enough. Daily analytics eats time and changes no decision.", "Save and pick your five"),
      ]},
    ],
  },
  {
    id: "money",
    title: "Money and finance",
    decks: [
      { id: "fin-1", title: "Where the money goes", slides: [
        cover("audit", "Tracked spending for a month. Found $400", "where it hid →"),
        say("find 1", "Small subscriptions", "Eight of them, a few dollars each, charged silently. Over a year it is a holiday.", "Small is invisible monthly"),
        say("find 2", "Weekday food out", "Not restaurants — coffee and lunches. The sum only appears when you add the month up.", "Add it up, do not estimate"),
        say("the point", "Track a month, do not budget", "Budgets are abandoned in two weeks. A one-off count teaches more and needs no willpower.", "Save and count your month"),
      ]},
      { id: "fin-2", title: "Your emergency fund", slides: [
        cover("basics", "How much you actually need", "counted honestly →"),
        say("not income", "Count spending, not earnings", "The fund covers costs, not salary. Different numbers, and the second is usually smaller.", "Costs, not income"),
        say("how much", "Three months minimum, six is calm", "Three covers a gap between jobs. Six covers a gap with a repair or an illness.", "Three is the floor"),
        say("the point", "Do not invest before it exists", "Otherwise the first breakdown forces a sale at the worst possible moment.", "Save and count yours"),
      ]},
      { id: "fin-3", title: "Beginner investing mistakes", slides: [
        cover("mistakes", "5 mistakes that cost me a year", "one at a time →"),
        say("mistake 1", "Started without a fund", "The first unexpected bill forced a sale at a loss. Order matters more than asset choice.", "Fund first"),
        say("mistake 2", "Checked it daily", "Daily swings make you act. Decisions made from fear cost more than any fee.", "Look less, lose less"),
        say("the point", "Boring works", "Regularity and time beat timing. That holds across every data set anyone has run.", "Save and sit still"),
      ]},
      { id: "fin-4", title: "Saving when it never works", slides: [
        cover("habit", "I saved what was left. Nothing was left", "what changed →"),
        say("rule", "Yourself first, everything else after", "Move it on payday, not at month end. There is never anything left at month end.", "Payday, not month end"),
        say("how much", "Start with an amount you will not notice", "Five percent held for a year beats twenty abandoned in a month.", "Small and always"),
        say("the point", "Automate it", "Manual transfers get forgotten. A standing order does not forget and does not argue.", "Save and set it up"),
      ]},
      { id: "fin-5", title: "Debt: what to count", slides: [
        cover("debt", "I compared rates. I should have compared this", "what exactly →"),
        say("not the rate", "Count the overpayment in currency", "Percentages hide the scale. “14% a year” and “$3,800 more” are the same thing said differently.", "Currency is honest"),
        say("order", "Clear the most expensive first", "Not the smallest and not the most annoying. The expensive one grows while you pay others.", "Expensive goes first"),
        say("the point", "Overpay to shorten the term", "Not the instalment. The difference in total cost is large and rarely asked about.", "Save and recount"),
      ]},
      { id: "fin-6", title: "Finances when self-employed", slides: [
        cover("freelance", "Earned $2,000. Saved nothing", "step by step →"),
        say("step 1", "Three accounts, not one", "Tax, fund, life. While it sits in one pile it all feels like yours.", "Split before you spend"),
        say("step 2", "Set tax aside immediately", "Not at quarter end. By then the money is gone and you borrow from yourself.", "Tax is not your money"),
        say("the point", "Uneven income, even costs", "Average over six months, live on the worst month. Then a good month becomes a reserve.", "Save and split the accounts"),
      ]},
      { id: "fin-7", title: "Subscription drain", slides: [
        cover("small stuff", "Eight subscriptions. I use two", "how to check yours →"),
        say("check", "List them from the statement", "Not from memory. Half will be a discovery you have paid for all year.", "Statement, not memory"),
        say("rule", "Cancel now, not later", "“I will cancel later” is another year of payments. Cancelling takes two minutes.", "Now or never"),
        say("the point", "Think in years", "Three dollars a month is thirty-six a year. In yearly form the decision takes a second.", "Save and open your statement"),
      ]},
      { id: "fin-8", title: "Talking money at home", slides: [
        cover("relationships", "We argued about spending. One question helped", "which →"),
        say("the question", "“What are we saving for?”", "An argument about spending is almost always an argument about different goals.", "A shared goal ends it"),
        say("format", "Once a month, twenty minutes", "Not in the middle of an argument and not when the money runs out. Scheduled and calm.", "Scheduled, not in a fight"),
        say("the point", "A joint account is optional", "Separate works too, if it is clear who covers what. Clarity matters, not the format.", "Save and pick a date"),
      ]},
      { id: "fin-9", title: "When income stops", slides: [
        cover("crisis", "Lost my main income. What I did", "week by week →"),
        say("week 1", "Count how long it lasts", "An exact number instead of dread. It is almost always longer than day one suggests.", "A number beats panic"),
        say("week 2", "Cut the large, not the small", "Skipping coffee saves nothing. Rent, subscriptions and payment schedules save something.", "Large items decide"),
        say("the point", "Call the bank before you miss a payment", "After a missed payment terms get worse. Before, they almost always negotiate.", "Save just in case"),
      ]},
      { id: "fin-10", title: "Money myths", slides: [
        cover("myths", "4 myths that stop people saving", "one at a time →"),
        say("myth 1", "“Saving small amounts is pointless”", "The habit matters more than the sum. Five dollars a month is about the mechanism.", "Mechanism beats amount"),
        say("myth 2", "“Clear debt first, save later”", "Without a fund any breakdown puts you back in debt. They run in parallel, slower but safer.", "Parallel, not sequential"),
        say("the point", "Starting beats starting right", "A perfect plan postponed a year loses to an average one started today.", "Save and start small"),
      ]},
    ],
  },
  {
    id: "fitness",
    title: "Fitness",
    decks: [
      { id: "fit-1", title: "Why the weight will not move", slides: [
        cover("teardown", "Training three times a week. Weight unchanged", "5 reasons →"),
        say("reason 1", "You count workouts, not food", "An hour in the gym burns less than one snack adds. The order of impact is not what it feels like.", "Food decides more"),
        say("reason 2", "Weight is the wrong measure", "Water, muscle, salt last night. Watch measurements and how clothes sit.", "A tape is honester than scales"),
        say("the point", "Judge by the month", "A week shows nothing. Bodies change slower than you want and faster than you think.", "Save and measure in a month"),
      ]},
      { id: "fit-2", title: "How to start and not quit", slides: [
        cover("start", "Quit six times. The seventh stuck", "what changed →"),
        say("mistake", "Started with five sessions a week", "Week two you miss one, week three you feel like a failure, week four it is over.", "Too much never sticks"),
        say("what works", "Two sessions you cannot miss", "Short, same days every week. Habits are built by a schedule, not by willpower.", "Schedule beats motivation"),
        say("the point", "A missed session is not a failure", "You missed, you returned. People quit over the conclusion they draw, not the miss.", "Save and start with two"),
      ]},
      { id: "fit-3", title: "Beginner gym mistakes", slides: [
        cover("gym", "6 mistakes visible from the door", "one at a time →"),
        say("mistake 1", "Weight before technique", "Bad form with heavy weight is not training, it is a queue at the physiotherapist.", "Technique first"),
        say("mistake 2", "A program written for another body", "It assumed another level, schedule and goal. Your job is to adapt it, not repeat it.", "Their program is not yours"),
        say("the point", "Write down what you did", "Without records you cannot see progress and in six months you are still in place.", "Save and start a log"),
      ]},
      { id: "fit-4", title: "Training at home", slides: [
        cover("home", "20 minutes at home. No equipment", "the plan →"),
        say("basis", "Five movements cover the body", "Squat, push, pull, plank, lunge. Everything else is a variation of those five.", "Five, not fifty"),
        say("load", "Change tempo, not reps", "A slow descent is harder than a fast repetition. That is how load grows without iron.", "Tempo replaces weight"),
        say("the point", "Three times a week, twenty minutes", "More than zero times for an hour. Compare with reality, not with the ideal.", "Save and try today"),
      ]},
      { id: "fit-5", title: "How much protein", slides: [
        cover("nutrition", "I counted calories. I missed the main thing", "what →"),
        say("the number", "1.6 grams per kilo of bodyweight", "A guide for people who train. Below that, muscle leaves alongside fat.", "1.6 g per kg"),
        say("in practice", "It is more than it sounds", "Count one ordinary day. Almost everyone lands at half the target.", "Count one day"),
        say("the point", "Protein holds off hunger", "The side effect matters more than the main one: on target you snack less.", "Save and count your day"),
      ]},
      { id: "fit-6", title: "Sleep and results", slides: [
        cover("recovery", "Added an hour of sleep. Results improved", "why →"),
        say("what happens", "Muscle grows outside the gym", "Training is the request. The body answers in sleep, and without sleep there is no answer.", "The gym asks, sleep answers"),
        say("shortfall", "It pulls you toward sugar", "Not weak character but hormones. Short sleep measurably raises the pull to fast carbohydrates.", "Cravings are lost sleep"),
        say("the point", "An hour of sleep beats supplements", "And costs nothing. Start there, not at the supplement shelf.", "Save and go to bed earlier"),
      ]},
      { id: "fit-7", title: "How not to break a diet", slides: [
        cover("relapse", "I broke every Friday. Then I understood", "what was wrong →"),
        say("cause", "The deficit was too steep", "The body takes it back within two weeks, usually in one evening. That is not weakness.", "A steep deficit eats itself"),
        say("fix", "Leave room for what you love", "Two hundred calories a day for the thing you like. Bans create relapses, not discipline.", "Bans create relapses"),
        say("the point", "Slow means permanent", "Half a kilo a week stays off. Three comes back with interest.", "Save and slow down"),
      ]},
      { id: "fit-8", title: "The warm-up everyone skips", slides: [
        cover("injury", "Skipped warm-ups for a year. Paid with my back", "what to do →"),
        say("why", "It is preparation, not stretching", "The job is to raise temperature and wake the right muscles, not stretch cold ones.", "Warm up, do not stretch"),
        say("how long", "Five minutes decide it", "A light version of what you are about to do. Not a ritual — the first sets, unloaded.", "Five minutes beats a month off"),
        say("the point", "Stretch afterwards", "On warm muscle it works, on cold it harms. Order matters more than presence.", "Save and stop skipping"),
      ]},
      { id: "fit-9", title: "How to measure progress", slides: [
        cover("tracking", "Scales lie. Here is what to use", "4 ways →"),
        say("way 1", "The same photo once a month", "Same light, same pose, same time of day. Mirrors deceive, photographs do not.", "Photos beat mirrors"),
        say("way 2", "Working weights and reps", "If they grow, it is working. That shows up before the reflection changes.", "Strength moves first"),
        say("the point", "Monthly, not daily", "Daily measurements show noise, not movement. And ruin your mood for nothing.", "Save and measure monthly"),
      ]},
      { id: "fit-10", title: "Training myths", slides: [
        cover("myths", "5 myths that slow results", "one at a time →"),
        say("myth 1", "“Fat turns into muscle”", "Different tissues. One leaves, the other grows — parallel processes, not a transformation.", "Two processes, not one"),
        say("myth 2", "“Abs work removes belly fat”", "Fat does not go locally. The muscle grows under a layer; the layer goes with food.", "Spot reduction does not exist"),
        say("the point", "Boring works", "Consistency, sleep, protein. Everything flashy that promises speed is selling, not training.", "Save and test it yourself"),
      ]},
    ],
  },
  {
    id: "psychology",
    title: "Psychology",
    decks: [
      { id: "psy-1", title: "How to stop postponing", slides: [
        cover("procrastination", "Postponed for a year. One rule fixed it", "which →"),
        say("cause", "It is not laziness", "People postpone what they cannot see how to start. The brain avoids uncertainty, not work.", "Unclear means frightening"),
        say("rule", "A first step of two minutes", "Not “write the report” but “open a document and name the file”. Starting removes resistance.", "Two minutes, not the task"),
        say("the point", "Break it down until it is silly", "If the step still frightens you, it is too big. Break it down until it is obvious.", "Save and take the first step"),
      ]},
      { id: "psy-2", title: "How to set boundaries", slides: [
        cover("boundaries", "I said yes to everyone. Then I said no", "step by step →"),
        say("step 1", "Refuse without explaining", "A long explanation sounds like an invitation to argue. A short “I cannot” closes it.", "Shorter is firmer"),
        say("step 2", "Offer what you can do", "A refusal plus an alternative does not damage the relationship. People remember the offer.", "Refuse with an alternative"),
        say("the point", "The first times feel awkward", "Then it becomes ordinary. Awkwardness is the entry fee, not a subscription.", "Save and try it once"),
      ]},
      { id: "psy-3", title: "Nerves before something big", slides: [
        cover("nerves", "I shook before every talk. What helped", "3 devices →"),
        say("device 1", "Name exactly what you fear", "Not “nervous” but “afraid of forgetting the middle”. A named fear shrinks to a task.", "A name shrinks it"),
        say("device 2", "Learn the first thirty seconds", "By heart. After that momentum takes over and the body settles on its own.", "First 30 seconds by heart"),
        say("the point", "The nerves do not leave", "They become useful. The task is not to remove them but to stop treating them as a problem.", "Save before your talk"),
      ]},
      { id: "psy-4", title: "Listening, not waiting your turn", slides: [
        cover("conversation", "I thought I listened. I was waiting for a pause", "the difference →"),
        say("the tell", "You compose a reply while they speak", "Then you are waiting, not listening. People feel it even when they cannot name it.", "Compose it afterwards"),
        say("the fix", "Say it back in your own words", "“So what you mean is...” is the most underrated sentence. It listens and it checks.", "Paraphrase, do not nod"),
        say("the point", "Nobody asked for advice", "Usually people need to be heard. Advice is about you, not about them.", "Save and try it today"),
      ]},
      { id: "psy-5", title: "Impostor syndrome", slides: [
        cover("doubt", "“They will find me out.” What to do", "step by step →"),
        say("truth", "Most competent people have it", "The feeling does not measure competence. It measures the gap between knowing and realising.", "A feeling is not a fact"),
        say("device", "Keep a list of what you did", "Memory keeps the misses and deletes the wins. A list restores the other half.", "Write down what worked"),
        say("the point", "It does not pass, you live with it", "It does not get in the way unless you mistake it for an assessment.", "Save and start the list"),
      ]},
      { id: "psy-6", title: "How to end an argument", slides: [
        cover("conflict", "We argued for hours. One sentence stops it", "which →"),
        say("the sentence", "“What are we actually arguing about?”", "Ten minutes in, an argument is rarely about the original thing. The question returns it.", "Return to the subject"),
        say("rule", "A pause is not losing", "Twenty minutes apart changes the conversation more than any argument does.", "A pause beats an argument"),
        say("the point", "There is nothing to win", "With someone close, winning is losing. The goal is to understand, not to win.", "Save for next time"),
      ]},
      { id: "psy-7", title: "Making decisions", slides: [
        cover("choices", "I deliberated for a month. Three questions helped", "which →"),
        say("question 1", "Will this matter in a year?", "Most decisions will not. Seeing that removes half the agony immediately.", "A year shrinks small things"),
        say("question 2", "Is it reversible?", "Reversible decisions are made fast. Only the irreversible ones deserve long thought.", "Reversible: decide quickly"),
        say("the point", "Not deciding is a decision", "Usually the worst one: you get the consequences without having chosen them.", "Save before your next choice"),
      ]},
      { id: "psy-8", title: "Tiredness that will not lift", slides: [
        cover("energy", "Slept eight hours and stayed tired", "what it was →"),
        say("cause", "Tiredness is not always about load", "Sometimes it is about meaninglessness: a lot of motion, no visible result.", "Meaning beats hours"),
        say("check", "What did you finish this week?", "If there is no answer, rest is not the problem. Nothing is being completed.", "Finishing restores"),
        say("the point", "Rest does not cure burnout", "A holiday postpones it. What cures it is changing what you return to.", "Save and answer honestly"),
      ]},
      { id: "psy-9", title: "Asking for help", slides: [
        cover("asking", "Did not ask for help for 30 years", "what changed →"),
        say("why it is hard", "It feels like a burden", "In fact people like being useful. A declined request is not a declined relationship.", "A request is not a burden"),
        say("how to ask", "Specific and bounded", "“Help me” frightens by scale. “Look at this for twenty minutes on Thursday” does not.", "Specifics remove fear"),
        say("the point", "Asking brings people closer", "It reads as trust. Someone who never asks reads as closed, not as strong.", "Save and ask once"),
      ]},
      { id: "psy-10", title: "Comparing yourself to others", slides: [
        cover("feeds", "I compared myself to a feed. What helped", "3 thoughts →"),
        say("thought 1", "You see the result, not the road", "Feeds show outcomes. A year of doubt and three failures do not fit in the frame.", "An outcome is not an example"),
        say("thought 2", "Compare with yourself a year ago", "The only honest comparison. Every other one is with people at a different point.", "Your own last year"),
        say("the point", "Unfollow what hurts", "Do not endure it heroically. A feed is a choice, not the weather.", "Save and clean your feed"),
      ]},
    ],
  },
  {
    id: "beauty",
    title: "Beauty and skincare",
    decks: [
      { id: "bty-1", title: "Skincare that works", slides: [
        cover("basics", "A shelf of 12 bottles. Three worked", "which →"),
        say("basis", "Cleanse, moisturise, protect", "Three steps cover almost everything. The rest is an add-on that does nothing without the base.", "Base before actives"),
        say("protection", "Not only in summer", "Sun works all year and through windows. It is the one step with proven effect on ageing.", "All year, not on holiday"),
        say("the point", "Change one product at a time", "Otherwise a reaction has no identifiable cause. Two weeks per new product, minimum.", "Save and audit your shelf"),
      ]},
      { id: "bty-2", title: "Skincare mistakes", slides: [
        cover("mistakes", "6 habits that damage skin", "one at a time →"),
        say("mistake 1", "Cleansing too often", "Squeaky clean means the barrier is gone. Skin answers with oil and irritation.", "Squeaky clean is damage"),
        say("mistake 2", "Mixing strong actives", "Everything at once in one evening gives you a broken barrier, not results.", "Not all in one evening"),
        say("the point", "Boring and regular", "Skincare works through time, not ingredients. Three months of the same beats a shelf of new.", "Save and simplify"),
      ]},
      { id: "bty-3", title: "How to read an ingredients list", slides: [
        cover("labels", "I read a label in 20 seconds", "in this order →"),
        say("rule 1", "Order matters", "The first five ingredients are nearly the whole bottle. An active at the end changes nothing.", "The first five decide"),
        say("rule 2", "“Paraben-free” is not a property", "It is marketing. Packaging says what sells, not what works.", "A claim is not a formula"),
        say("the point", "Price is not effect", "The same active appears in products that differ tenfold in price.", "Save before you buy"),
      ]},
      { id: "bty-4", title: "Skincare in 5 minutes", slides: [
        cover("minimum", "5 minutes in the morning. What fits", "step by step →"),
        say("morning", "Wash, moisturise, protect", "Three moves, ninety seconds. Everything else is optional and often gets in the way.", "Three steps, not ten"),
        say("evening", "Remove and moisturise", "The main evening action is removing what was on your face. The rest is secondary.", "Removing beats applying"),
        say("the point", "A short routine you actually do", "It beats a long one abandoned in a week. Count in months, not in steps.", "Save and shorten yours"),
      ]},
      { id: "bty-5", title: "Hair: what changes everything", slides: [
        cover("hair", "Expensive masks did nothing. Something else did", "what →"),
        say("first", "Water temperature", "Hot water does more damage than any mask undoes. Warm water shows a difference in a month.", "Warm, not hot"),
        say("second", "How you dry it", "Rubbing with a towel breaks the strand. Blotting instead is free and visible.", "Blot, do not rub"),
        say("the point", "Free things work first", "Habits, then products. In the other order the products never get a chance.", "Save and change one habit"),
      ]},
      { id: "bty-6", title: "Makeup that lasts", slides: [
        cover("makeup", "Lasts until evening. Three reasons", "slide by slide →"),
        say("reason 1", "Skin preparation", "Longevity is decided before application. Nothing holds on skin that is dry or oily.", "The primer is your skin"),
        say("reason 2", "Thin layers", "One thick layer slides off faster than two thin ones. The rule holds for everything.", "Thinner lasts longer"),
        say("the point", "Fewer products, better technique", "Expensive makeup does not save technique. Technique saves inexpensive makeup.", "Save and try layers"),
      ]},
      { id: "bty-7", title: "What does not work", slides: [
        cover("myths", "5 products I wasted money on", "and why →"),
        say("first", "Pore-shrinking products", "Pore size does not change. What changes is visibility, and that comes from cleansing.", "Pores do not shrink"),
        say("second", "Scrubs with coarse particles", "They injure rather than clean. Skin answers with inflammation that outlasts the scrub.", "Scratches are not cleansing"),
        say("the point", "Instant promises are a warning", "Skin renews over weeks. Anything promising overnight works on appearance, not condition.", "Save before your next purchase"),
      ]},
      { id: "bty-8", title: "Winter skincare", slides: [
        cover("season", "Skin behaves differently in winter", "3 rules →"),
        say("rule 1", "Richer, not greasier", "The job is to hold water in, not to coat in oil. Look for a barrier, not a shine.", "Hold, do not coat"),
        say("rule 2", "Protection still applies", "Snow reflects more light than asphalt. Winter is when people skip it, wrongly.", "Winter does not cancel it"),
        say("the point", "Heating dries more than frost", "Most of winter your skin suffers indoors. A humidifier outperforms a cream.", "Save and switch it on"),
      ]},
      { id: "bty-9", title: "Choosing a professional", slides: [
        cover("salon", "I choose by three signs", "which →"),
        say("sign 1", "They ask questions", "Someone who starts without your history is a lottery. Questions matter more than a portfolio.", "Questions beat photos"),
        say("sign 2", "They are willing to talk you out of it", "“That will not suit you” is worth more than agreement to everything.", "A refusal signals experience"),
        say("the point", "Profile photos are not proof", "Look at client photos in reviews, not studio shots under perfect light.", "Save before you book"),
      ]},
      { id: "bty-10", title: "A shelf for $40", slides: [
        cover("budget", "A full routine for $40", "item by item →"),
        say("do not save on", "Sun protection", "The one item with proven effect. Better to pay more and use it every day.", "Not the place to economise"),
        say("you can save on", "Cleanser and moisturiser", "The gap between cheap and expensive is small. Read the formula, not the price.", "Formula over price"),
        say("the point", "Three products instead of twelve", "The result is usually better: fewer reactions and a clear picture of what works.", "Save and build your shelf"),
      ]},
    ],
  },
  {
    id: "food",
    title: "Food and cooking",
    decks: [
      { id: "food-1", title: "Cooking for the week", slides: [
        cover("prep", "Two hours on Sunday. A week without cooking", "how →"),
        say("rule", "Cook components, not dishes", "Grain, protein and vegetables separately. They assemble into five lunches, not one you tire of.", "Components, not dishes"),
        say("storage", "Sauce goes separately", "Dressed food falls apart in a day. Kept apart it holds four and still looks fresh.", "Dress at the last moment"),
        say("the point", "Do not cook for seven days", "Cook for four. By day five everything is tiresome and the food goes in the bin.", "Save and try it Sunday"),
      ]},
      { id: "food-2", title: "Breakfast in 5 minutes", slides: [
        cover("mornings", "5 breakfasts faster than the coffee", "the list →"),
        say("basis", "Protein in the morning is about the day", "A carbohydrate breakfast pulls you to a snack within an hour. Protein holds until lunch.", "Protein holds until lunch"),
        say("prep", "What to do the night before", "Soak, chop, whisk. In the morning you only assemble, and that changes everything.", "Evening saves the morning"),
        say("the point", "A skipped breakfast comes back", "Usually in the evening and with interest. Not discipline — the body takes what it missed.", "Save and pick one"),
      ]},
      { id: "food-3", title: "Kitchen mistakes", slides: [
        cover("mistakes", "7 reasons it tastes flat", "one at a time →"),
        say("mistake 1", "A cold pan", "Food sticks and steams instead of frying. Preheating solves half of all crust problems.", "Preheat for crust"),
        say("mistake 2", "Everything in at once", "A crowded pan makes steam, not heat. Two batches finish faster than one crowded one.", "Crowded means boiled"),
        say("the point", "Salt at the right time", "Early salt draws out water, late salt has no time to work. The difference is audible.", "Save and try it tonight"),
      ]},
      { id: "food-4", title: "Always in the cupboard", slides: [
        cover("staples", "10 things that always make dinner", "the list →"),
        say("rule", "Long shelf life and five uses", "Grain, eggs, tinned chickpeas, frozen vegetables. Each works in different dishes.", "Versatile beats delicious"),
        say("what it buys", "Dinner without a shop trip", "Even on the day you have nothing left. That is exactly the day people order delivery.", "Staples save the evening"),
        say("the point", "Restock one at a time", "Not a supermarket raid but one extra item per normal shop. The shelf builds itself.", "Save the list"),
      ]},
      { id: "food-5", title: "Eating less sugar", slides: [
        cover("habit", "Cut sugar without willpower", "step by step →"),
        say("step 1", "Do not look at sweets", "Most sugar arrives in sauces, bread and drinks. Sweets are the visible minority.", "Sugar hides in savoury"),
        say("step 2", "Replace, do not ban", "An empty space gets filled by the body, and not by what you planned. Prepare the replacement.", "Replace, do not ban"),
        say("the point", "Taste changes in three weeks", "What felt normal starts to taste sickly. That is the result.", "Save and hold three weeks"),
      ]},
      { id: "food-6", title: "Cooking with no energy", slides: [
        cover("exhausted", "Dinner in 10 minutes from nothing", "3 options →"),
        say("option 1", "Eggs, any way", "Five minutes, protein, done. Boring right up to the evening you have nothing left.", "Eggs save the evening"),
        say("option 2", "Frozen vegetables straight into the pan", "No defrosting, high heat. Faster than waiting for delivery and a fraction of the cost.", "Frozen beats delivery"),
        say("the point", "Simple is not bad", "Food made of three ingredients feeds you the same. The ritual is not needed daily.", "Save for that evening"),
      ]},
      { id: "food-7", title: "How to stop binning food", slides: [
        cover("waste", "I binned $50 a month. I counted", "what changed →"),
        say("step 1", "One “eat first” shelf", "Everything near its date moves there. People forget because they cannot see, not because they do not care.", "Visible gets eaten"),
        say("step 2", "Write the list at the fridge", "Half of purchases are a second packet of something already there. Checking takes a minute.", "A minute saves a purchase"),
        say("the point", "Plan four dinners of seven", "The other three get covered by leftovers and life. A plan for all seven never survives.", "Save and start the shelf"),
      ]},
      { id: "food-8", title: "Spices: where to start", slides: [
        cover("flavour", "5 spices instead of thirty jars", "which →"),
        say("basis", "Salt, pepper, paprika, garlic, acid", "Acid means lemon or vinegar. It lifts flavour where it feels like salt is missing.", "Missing salt? Add acid"),
        say("rule", "Dry into fat, fresh at the end", "Dry spices open in fat and heat; fresh ones lose everything to it.", "Order changes flavour"),
        say("the point", "Thirty jars sit and go stale", "Spices fade within a year. Five that work beat a shelf opened twice.", "Save and build your five"),
      ]},
      { id: "food-9", title: "How to read a label", slides: [
        cover("shopping", "I read a label in 15 seconds", "in order →"),
        say("step 1", "The ingredients, not the front", "“Natural” and “farm” mean nothing. Only the ingredient list means anything.", "Turn the packet over"),
        say("step 2", "Sugar per 100 grams", "Per hundred, not per portion: the producer decides the portion size.", "Only per 100 compares"),
        say("the point", "A short list is not always better", "What is in it matters more. A long list on yoghurt and on biscuits mean different things.", "Save before shopping"),
      ]},
      { id: "food-10", title: "Coffee at home", slides: [
        cover("coffee", "Home coffee was worse. It was not the machine", "what it was →"),
        say("first", "Bean freshness", "Ground coffee lives minutes, beans live weeks. That changes taste more than any equipment.", "Beans beat machines"),
        say("second", "Water", "Coffee is 98% water. Hard water gives a flat cup with any bean and any grind.", "Bad water ruins everything"),
        say("the point", "Scales matter more than a machine", "The same ratio every day gives repeatability. Without it the taste is random.", "Save and buy scales"),
      ]},
    ],
  },
  {
    id: "travel",
    title: "Travel",
    decks: [
      { id: "trv-1", title: "How to pack", slides: [
        cover("packing", "40 flights. I pack in 20 minutes", "how →"),
        say("rule 1", "Count outfits, not items", "Three bottoms and four tops make twelve outfits. Counting items means carrying extras.", "Outfits, not items"),
        say("rule 2", "Wear the heavy things", "Shoes and a coat fill half a case. On the plane they weigh nothing.", "Heavy things get worn"),
        say("the point", "Write the list once", "Do not rebuild it every trip. One note saves an evening before every departure.", "Save and write yours"),
      ]},
      { id: "trv-2", title: "Cheaper flights", slides: [
        cover("tickets", "I fly cheaper, and not because of secret sites", "because of this →"),
        say("first", "Flexible dates beat any site", "The gap between Tuesday and Friday is bigger than the gap between search engines.", "The day beats the site"),
        say("second", "The neighbouring airport", "An hour on a bus often halves the fare. Check both before you book.", "Check both airports"),
        say("the point", "Earlier is not always cheaper", "There is a window, not a rule. Watch the price for a fortnight before deciding.", "Save before you book"),
      ]},
      { id: "trv-3", title: "Your first day in a city", slides: [
        cover("route", "The first day decides the whole trip", "how to build it →"),
        say("step 1", "Walk, with no plan", "The first three hours are for walking. A city is memorised by feet, not by a screen.", "Feet remember better"),
        say("step 2", "One anchor per day", "One place that must happen, the rest as it goes. Five points a day turns a trip into work.", "One anchor, not five"),
        say("the point", "Eat where locals queue", "Not where the menu is prettiest in English. The rule holds almost everywhere.", "Save before you go"),
      ]},
      { id: "trv-4", title: "Trip mistakes", slides: [
        cover("mistakes", "6 mistakes that ruin a holiday", "one at a time →"),
        say("mistake 1", "An hour-by-hour plan", "A scheduled holiday tires you more than work. Leave half of every day empty.", "Half the day stays empty"),
        say("mistake 2", "Saving on the first night", "A bad first day sets the tone for everything. This is where to overpay.", "Not the night to economise"),
        say("the point", "Fewer cities, more time", "Three cities in a week is a week in transit. One city is remembered better than three.", "Save before planning"),
      ]},
      { id: "trv-5", title: "What goes in your carry-on", slides: [
        cover("carry-on", "What is always in my hand luggage", "the list →"),
        say("essential", "A change of clothes and a charger", "Luggage gets lost and connections fail. Those two cover the first day without a case.", "One day without a case"),
        say("often forgotten", "Medication and copies of documents", "A pharmacy may be shut, and copies save the day when everything else goes wrong.", "Copies, kept separately"),
        say("the point", "The one-bag rule", "If your carry-on is over five kilos you are carrying “just in case”, not necessities.", "Save and pack yours"),
      ]},
      { id: "trv-6", title: "Travelling with a child", slides: [
        cover("family", "Flew with a child. What actually helps", "from experience →"),
        say("first", "Routine beats sightseeing", "Sleep and meals at the usual times save the day. Everything else fits around them.", "Routine holds the trip"),
        say("second", "A new small thing for the journey", "Not a favourite toy from home but an unfamiliar one. Novelty holds attention far longer.", "New beats favourite"),
        say("the point", "Plan half as much", "And treat that as normal rather than as defeat. Fewer points, more trip.", "Save before you fly"),
      ]},
      { id: "trv-7", title: "How not to overspend", slides: [
        cover("budget", "I budgeted the trip and got one thing wrong", "what →"),
        say("mistake", "The journey either side", "Taxis to the airport, baggage, food in transit. Up to a third of the budget, never counted.", "Transit is a third"),
        say("device", "A daily limit, not a total", "A total runs out on day three. A daily limit distributes itself.", "Per day, not per trip"),
        say("the point", "Cash for the first day", "Cards fail, machines are out of service. One day in cash removes the risk.", "Save before you travel"),
      ]},
      { id: "trv-8", title: "Choosing where to stay", slides: [
        cover("stays", "Three filters, then everything else", "which →"),
        say("filter 1", "The area, not the photos", "A beautiful flat in an awkward area costs you an hour a day in transit.", "Area beats interior"),
        say("filter 2", "Reviews from the last three months", "Old reviews describe different owners and a different renovation. Read recent ones.", "Recent reviews, not the score"),
        say("the point", "Check the cancellation terms", "Plans change more often than people expect. Free cancellation is worth its price.", "Save before booking"),
      ]},
      { id: "trv-9", title: "Photographing a trip", slides: [
        cover("photos", "Brought home 800 photos. Looked at 5", "what changed →"),
        say("rule 1", "Photograph people, not only views", "Views look the same for everyone. In a year you will look at who was there.", "People are remembered"),
        say("rule 2", "Sort them in the evening", "Twenty minutes a day and you do not come home to a thousand untouchable frames.", "Evening beats never"),
        say("the point", "One day without the phone", "Sometimes just look. A trip lived through a screen is remembered worse.", "Save before your next trip"),
      ]},
      { id: "trv-10", title: "Visa-free destinations", slides: [
        cover("destinations", "A list of visa-free destinations", "and how to check →"),
        say("rule", "Check before every trip", "Conditions change several times a year. Last year's list is a hint, not a source.", "Check every single time"),
        say("what to check", "Not only the visa", "Passport validity, return ticket, proof of accommodation. That is what is asked at the border.", "A visa is not the only condition"),
        say("the point", "Use the official source", "Social posts age faster than the rules. Check with the consulate, not the feed.", "Save and check before flying"),
      ]},
    ],
  },
];
